---
title: "BMW"
author: "Jacque Wilfred Arokiaraj"
date: "March 15, 2019"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(twitteR)
library(ROAuth)
library(RCurl)
library(plyr)
library(tm)
library(stringr)
library(ggplot2)
library(wordcloud)
require('devtools')
```

```{r}
install_github('mananshah99/sentR')
```


```{r}
consumer_key <- "nvJVFbbFlFsjVkqRkjnKCo2S4"
consumer_secret <- "YufdDILJ07CXddZCSc0ZOtpNCjg1GgH1ZRv1yUMwpJcAyUYhsG"
access_token <- "839168786695614464-C74488LDI8xG1YGcZ6Aw2JSEgsgRnzQ"
access_secret <- "QeOY7n5mJcIwXCZG1ghhWPoNllkzLJsiQTBi6skCLEFFF"
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
1
```
```{r}
cities <- c("NYC, NY","San Francisco, CA","Miami, FL","Austin, TX","Atlanta, GA","Columbia, SC")
coords <- c("40.7128,-74.0059","37.7749,-122.4194","25.7617,-80.1918","30.2672,-97.7431","33.7490,-84.3880","34.0007,-81.0348")
score <- vector(mode="numeric", length=0)
type <- vector(mode="character", length=0)
city <- vector(mode="character", length=0)

for (i in 1:length(cities)) {
  tweets <- searchTwitter(paste("BMW","exclude:retweets",sep="+"), n=100, lang="en", geocode=paste(coords[i],"50mi",sep=","), resultType="recent")	
  tweets.text = lapply(tweets,function(t)t$getText())
  out <- classify.naivebayes(tweets.text)
  pos_score <- 0
	neg_score <- 0
	neut_score <- 0
	for (j in 1:(length(out) / 4)) {
	  sent <- out[j, "SENT"]
	  if (sent == "neutral") {
	    neut_score <- neut_score + 1
	    } else if (sent == "positive") {
				pos_score <- pos_score + 1
			} else if (sent == "negative") {
				neg_score <- neg_score + 1
			}
	  }
	city <- append(city, c(cities[i],cities[i],cities[i]))
	type <- append(type, "positive")
	score <- append(score, pos_score)
	type <- append(type, "negative")
	score <- append(score, neg_score)
	type <- append(type, "neutral")
	score <- append(score, neut_score)
	tweetTexts <-unlist(lapply(tweets, function(t) { t$text})) 
	words <- tolower(unlist(strsplit(tweetTexts, " ")))
	clean_words <- words[-grep("http|@|#|ü|ä|ö|&|<U+0001F60D>ick.|;", words)] 
	{plot.new()
	text(x=0.5, y=0.5, paste(cities[i]))} 
  clean_words <- str_replace_all(clean_words, "[[:punct:]]", " ")
	wordcloud(clean_words, min.freq=1,max.words=100,main=cities[i])
	}
dataFrame <- data.frame(Sentiment = factor(type), Location = factor(city, levels=cities), Frequency = score)
print(dataFrame)
print(paste("Bar chart for","BMW"))
ggplot(data=dataFrame, aes(x=Location, y=Frequency, fill=Sentiment)) + geom_bar(stat="identity", position=position_dodge())

```



